In [1]:
import numpy as np

In [2]:
np.zeros(5)
# creating an array

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(10)
np.ones(10)
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

converting a python list to numpy array

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# accessing elements in an array
a[3]

4

In [8]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi-dimensional array

In [9]:
np.zeros((5, 2))
# 5 => rows
# 2 => columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

Random generated arrays

In [21]:
# to fix the random numbers
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [22]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

Element wise operations

In [24]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [26]:
b + 1
# can also use "+,-,*,/, **" operations

array([1, 2, 3, 4, 5])

In [27]:
c = (10 + (b * 2)) ** 2 / 100
c

array([1.  , 1.44, 1.96, 2.56, 3.24])

comparison operators

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
a >= 2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [31]:
b > c

array([False, False,  True,  True,  True])

In [32]:
# to check which exact elements returns true for the comparison
b[b > c]

array([2, 3, 4])

In [33]:
np.__version__

'1.23.2'