In [1]:
import numpy as np

In [2]:
np.zeros(5)
# creating an array

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(10)
np.ones(10)
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

converting a python list to numpy array

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# accessing elements in an array
a[3]

4

In [8]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi-dimensional array

In [9]:
np.zeros((5, 2))
# 5 => rows
# 2 => columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

Random generated arrays

In [21]:
# to fix the random numbers
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [22]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

Element wise operations

In [24]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [26]:
b + 1
# can also use "+,-,*,/, **" operations

array([1, 2, 3, 4, 5])

In [27]:
c = (10 + (b * 2)) ** 2 / 100
c

array([1.  , 1.44, 1.96, 2.56, 3.24])

comparison operators

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
a >= 2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [31]:
b > c

array([False, False,  True,  True,  True])

In [32]:
# to check which exact elements returns true for the comparison
b[b > c]

array([2, 3, 4])

In [33]:
np.__version__

'1.23.2'

Vector operations

In [35]:
u = np.array([2,4,5,6])

In [36]:
2 * u

array([ 4,  8, 10, 12])

In [37]:
v = np.array([1,0,0,2])

In [38]:
u + v

array([3, 4, 5, 8])

In [39]:
u.shape

(4,)

In [44]:
w = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9],
  [1,4,7]
])

w.shape

(4, 3)

vector-vector multiplication

example:

u = [2,4,5,6]

v = [1,0,0,6]

`u . v` = `(2*1)+(4*0)+(5*0)+(6*2)` = `2+12` = 14

In [40]:
def vector_vector_multiplication(u, v):
  assert u.shape[0] == v.shape[0]
  
  n = u.shape[0]
  result = 0.0
  
  for i in range(n):
    result = result + u[i] * v[i]
  
  return result
  

In [41]:
vector_vector_multiplication(u, v)

14.0

In [42]:
u.dot(v)

14

In [46]:
U = np.array([
  [2,4,5,6],
  [1,2,1,2],
  [3,1,2,1]
])

In [49]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [50]:
v

array([1, 0, 0, 2])

In [52]:
U.shape[1] 


4

In [53]:
v.shape[0]

4

In [54]:
U.shape[1] == v.shape[0]

True

matrix vector multiplication

In [55]:
def matrix_vector_multiplication(U, v):
  assert U.shape[1] == v.shape[0]
  
  num_of_rows = U.shape[0]
  
  result = np.zeros(num_of_rows)
  
  for i in range(num_of_rows):
    result[i] = vector_vector_multiplication(U[i], v)
    
  return result

In [56]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

matrix-matrix multiplication

In [57]:
V = np.array([
  [1,1,2],
  [0,0.5,1],
  [0,2,1],
  [2,1,0]
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [58]:
def matrix_matrix_multiplication(U, V):
  assert U.shape[1] == V.shape[0]
  
  num_of_rows = U.shape[0]
  num_of_cols = V.shape[0]
  
  result = np.zeros((num_of_rows, num_of_cols))
  
  for i in range(num_of_cols):
    vi = U[:, i]
    Uvi = matrix_vector_multiplication(U, vi)
    result[:, i] = Uvi
  
  return result

In [59]:
matrix_matrix_multiplication(U, V)

AssertionError: 

In [60]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])